### ISSUE TITLE
Some questions about Gemini application

### ISSUE THREAD

**Issue by HelloWorldLTY** [MinxZ/Gemini#1]
Hi Mingxin, I am interested in your Gemini tool and I plan to use it to integrate co-expression data. Before doing that, I have some questions and I intend to check with you. Could you please help me? Thanks a lot.

1. I find that in the ipynb file related to new network.ipynb, there are codes marked as "unfinished", so if I intend to use new network, can I directly run the whole jupyter notebook to get the gene embeddings? 
2. I am confused about this equation in this original paper:
![image](https://user-images.githubusercontent.com/43333475/214053771-53789272-cd9c-4e4b-98cf-54a588470079.png)
I think the dim(Q) = n*n rather than Mn*n. Therefore, did you calculate many Q matrices here? Thanks.

**Comment by MinxZ** [comment]
I'm sorry for not getting back to you sooner. I am glad you are interested in our Gemini tool.
1. We are still working on the jupyter notebook. We will come up with either making a jupyter notebook for applications with new data or a procedure on how to use the existing python file with new data. Which way do you prefer?
2. Q is an nxn matrix. However, when calculating Q, we may need multiple Rs. These Rs need Mnn memory space. We use equation 3 to reduce the needed memory space to nn.

**Comment by HelloWorldLTY** [comment]
Hi Mingxin, many thanks for your reply. I think jupyter notebook is enough.

**Comment by MinxZ** [comment]
I added the jupyter notebook. Can you try with your own data, feel free to ask if you have any issues with the jupyter notebook.

**Comment by HelloWorldLTY** [comment]
Hi, I think I cannot find device as a keyword in mashup_multi() function, so if I intend to use cpu to test my data, what should I do? 

![image](https://user-images.githubusercontent.com/43333475/218178891-ab5a86ba-b700-4936-8d70-cac9a456327d.png)

Moreover, I take a look at the sample dataset, for my own dataset, I only have 0/1 valued co-expression network, and I did not have strength. Is it ok? Thanks a lot.

**Comment by MinxZ** [comment]
I'm sorry for not getting back to you sooner. I added support for devices: cuda, CPU, and mps(Apple's Metal Performance Shaders). For strength, you can only keep the connection with 1 and ignore 0. The strength will not affect the results a lot. You still need to add strength to the data, in your case, just set all strength to 1 is ok.

**Comment by HelloWorldLTY** [comment]
No need to say sorry, many thanks for your help~

**Comment by MinxZ** [comment]
Did you successfully apply this model to your data? If everything goes well, can I close this issue? Let me know if you have anything unclear when trying our model.

**Comment by HelloWorldLTY** [comment]
Oh sorry for my late reply. Yes I have solved the previous problem and it runs well. Thanks for your help again, and I can close this issue.
